# Fonts
font_family      FiraCode-Retina
font_size        14
bold_font        auto
italic_font      auto
bold_italic_font auto

mouse_hide_wait  2.0
cursor_shape     block

allow_hyperlinks yes
url_color        #0087bd
url_style        dotted

macos_option_as_alt yes
# Title bar
hide_window_decorations titlebar-only

# Background
background_opacity 0.85
background_blur 16

# Padding
window_padding_width 10
